name: Deploy to Google App Engine
# This is a simple workflow to build this Django project and deploy it as a Google App Engine application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
      - name: Configure development environment
        run: make init
      - id: build
        run: make build
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
